version: 0.2

phases:
  pre_build:
    commands:
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG nginx/
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"nignx-19","imageUri":"dmitiriy/artem_forever_nginx","portMappings":[{"containerPort":80,"hostPort":80}],"essential":true}]' > imagedefinitions.json
      - printf '[{"name":"apache","imageUri":"dmitiriy/artem_forever_apache","portMappings":[{"containerPort":8000,"hostPort":8000}],"essential":true}]' > imagedefinitions_apache.json
artifacts:
    files: 
      - imagedefinitions.json
      - imagedefinitions_apache.json


#DOCKERHUB_USERNAME dmitiriy
#DOCKERHUB_PASSWORD
#IMAGE_REPO_NAME dmitiriy/artem_forever_nginx
#IMAGE_TAG latest
