version: "3"
services:
  apache2host:
    build: apache
    ports:
      - 8000:8000
    networks:
      - Net1

  nginx:    
    build: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - Net1
      
networks:
  Net1: