version: "3"
services:
  apache2host:
    image: dmitiriy/artem_forever_apache:latest
    ports:
      - 8000:8000
    networks:
      - Net1


  nginx:    
    image: dmitiriy/artem_forever_nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - Net1
      
networks:
  Net1: